
CREATE OR REPLACE PROCEDURE TURKISHCOFFEE.QUESTION3
IS

CURSOR SOME_CURSOR IS
SELECT L.CODELOGI, L.NOMLOGI, L.INSTALLS
FROM LOGICIEL L;

CDLOG LOGICIEL.CODELOGI%TYPE;
NMLOG LOGICIEL.NOMLOGI%TYPE;
INST LOGICIEL.INSTALLS%TYPE;

CURSOR SOME_OTHER_CURSOR IS
SELECT X.POSTE.NSERIE
FROM TABLE (INST) X;

REFID POSTE_TRAVAIL.NSERIE%TYPE;

BEGIN
	OPEN SOME_CURSOR;
	FETCH SOME_CURSOR 
	INTO CDLOG, NMLOG, INST;
	WHILE (SOME_CURSOR%FOUND)
	LOOP
		OPEN SOME_OTHER_CURSOR;
		FETCH SOME_OTHER_CURSOR INTO REFID;
		WHILE (SOME_OTHER_CURSOR%FOUND)
		LOOP
			IF REFID = 'p2' THEN
				INSERT INTO LOGPOSTEP2 VALUES (CDLOG, NMLOG) ;
			END IF;
			
			FETCH SOME_OTHER_CURSOR INTO REFID;
		END LOOP;
		CLOSE SOME_OTHER_CURSOR;
		FETCH SOME_CURSOR 
		INTO CDLOG, NMLOG, INST;
	END LOOP;
	CLOSE SOME_CURSOR;
END QUESTION3;
