CREATE OR REPLACE PROCEDURE TURKISHCOFFEE.QUESTION2
IS

CURSOR SOME_CURSOR IS												--premier curseur destine pour la premiere boucle
	SELECT S. IND_IP, S. LOCAUX										--dans laquelle nous parcourons toutes les lignes
	FROM SEGMENT1 S;												--de la TABLE SEGEMENT1

INDIP SEGMENT1. IND_IP%TYPE;										--variables definies pour le premier FETCH
LCX SEGMENT1. LOCAUX%TYPE;											--variables definies pour le premier FETCH

CURSOR SOME_OTHER_CURSOR IS											--SECOND CURSEUR pour parcourir la TABLE imbriquee
SELECT X.LOCAL.NBUREAU												--FETCHEE dans la TABLE  temporaire LCX
FROM TABLE(LCX) X;

LOCAL_NB_TMP BUREAU.nbureau%TYPE;									-- VARIABLE pour le SECOND FETCH

BEGIN
	
	OPEN SOME_CURSOR;
	FETCH SOME_CURSOR INTO INDIP, LCX;
	WHILE (SOME_CURSOR%FOUND)
	LOOP
		OPEN SOME_OTHER_CURSOR;
		FETCH SOME_OTHER_CURSOR INTO LOCAL_NB_TMP;
		WHILE (SOME_OTHER_CURSOR%FOUND)
		LOOP
			--INSERER DANS SEGBUR LES VALEURS
			INSERT INTO SEGBUR VALUES (INDIP, LOCAL_NB_TMP);
		
			FETCH SOME_OTHER_CURSOR INTO LOCAL_NB_TMP;
		END LOOP;
		CLOSE SOME_OTHER_CURSOR;
		FETCH SOME_CURSOR INTO INDIP, LCX;
	END LOOP;
	CLOSE SOME_CURSOR;

END QUESTION2;