	CREATE OR REPLACE PROCEDURE TURKISHCOFFEE.QUESTION4
IS
CURSOR SOME_CURSOR IS
SELECT P.NSERIE, P.ADRESSEIP
FROM POSTE_TRAVAIL P;

NBLOG NUMBER;
ADR_IP POSTE_TRAVAIL.ADRESSEIP%TYPE;
NPST POSTE_TRAVAIL.NSERIE%TYPE;

BEGIN
	OPEN SOME_CURSOR;
	FETCH SOME_CURSOR INTO NPST,ADR_IP;
	WHILE SOME_CURSOR%FOUND 
	LOOP
		SELECT Count(*) INTO NBLOG
		FROM LOGICIEL l, THE (
			SELECT lg.INSTALLS
			FROM LOGICIEL lg
			WHERE l.CODELOGI=lg.CODELOGI) X 
		WHERE X.POSTE.nserie=NPST;
		IF NBLOG = 3 AND ADR_IP='02' THEN
				INSERT INTO nb_log_Poste_IP2
				VALUES (NPST);
		END IF;
		FETCH SOME_CURSOR INTO NPST,ADR_IP;
	END LOOP;
	CLOSE SOME_CURSOR;
END QUESTION4;